### ISSUE TITLE
Question: Need autostart ROM?

### ISSUE THREAD

**Issue by rtrimbler** [ThorstenBr/DAN2on3#1]
If I don't plan to use the Dan][ card in emulation mode, and I manually configure the slot number, do I even need the EEPROM installed?

**Comment by ThorstenBr** [comment]
Yes, it is still required. The driver uses it for identification, and the configuration utility also for communication. The 6502 code in the ROM can run on both, on Apple II and ///.
The original PCB mentioned a 27c512 ROM, but only 512bytes of ROM are required. So any of the smaller (pin compatible) devices of the series can be used. I personally use 8K EPROMs or EEPROMs (27c64/28c64).

There are going to be a number of updates for the Apple /// soon. An updated configuration utility is next. Eventually it should also allow direct bootstrapping of SD card volumes...
