### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by rtrimbler** [ThorstenBr/DAN2on3#3]
Could you create a new (prebuilt) "release" for version 2.1.1 please?

**Comment by Daniel102010** [comment]
Please!

**Comment by ThorstenBr** [comment]
No worries, here you go: https://github.com/ThorstenBr/DAN2on3/releases/tag/v2.1.0

I'm currently working on a few new features, including boot strapping from the card. So I had just been pushing some intermediate changes which were safe. I have more locally, so there will be more updates for the ///....
If anyone has a working color display for the Apple ///, let me know. I'd be interested to see how the menu looks. I have a PAL machine (which are unable to produce any valid PAL color video, AFAIK).

**Comment by rtrimbler** [comment]
Thanks! Downloaded it just now.
[image: Config2.1.jpg]

**Comment by rtrimbler** [comment]
![Config2 1](https://github.com/ThorstenBr/DAN2on3/assets/80604273/043bb8a6-6a4b-40d1-b25a-874b0047b245)
