### ISSUE TITLE
Documentation update request

### ISSUE THREAD

**Issue by rtrimbler** [ThorstenBr/DAN2on3#4]
I got the make process working on windows WSL2 with Ubuntu 22.04, but it l had to add python 2.7 to run a3driverutil.py. (Python 3.10.6 throws a bunch of errors on this file, but works fine otherwise.) In the driver Makefile it also specifies "python" on line 20, compared to "python3" on line 18. The readme.md file only mentions the need for python3.

JRE is required too. (To run AppleCommander. Neither python2 or JRE were included with my default Linux installation.)

Also, in the readme.md file section "Controller Volume Configuration" note it says "The menu now supports the flexible volume mapping, which is supported by newer firmware" - could you clarify which version of firmware added this? (Newer and older are kind of ambiguous.)

**Comment by ThorstenBr** [comment]
Thanks for spotting these. Indeed, Python2 is currently also required. I use Python3 for all my scripts. The a3driverutil.py is something I imported (from Rob Justice) and still based on older Python. It probably can be updated to be also compatible with Py3.
Concerning the firmware version: the description of the latest release has the version dependency described more specifically: https://github.com/ThorstenBr/DAN2on3/releases/tag/v2.1.0
I will update the main readme.
